version: 2

project_name: kubectl-resource_usage

before:
  hooks:
    - go mod tidy

builds:
  - id: kubectl-resource_usage
    main: ./cmd/kubectl-resource_usage
    binary: kubectl-resource_usage
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: r1ckyIn
    name: kubectl-resource-usage
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
