version: 2

project_name: kubectl-resource_usage

before:
  hooks:
    - go mod tidy

builds:
  - id: kubectl-resource_usage
    main: ./cmd/kubectl-resource_usage
    binary: kubectl-resource_usage
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: r1ckyIn
    name: kubectl-resource-usage
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  extra_files:
    - glob: .krew.yaml

krews:
  - name: resource-usage
    ids:
      - default
    repository:
      owner: r1ckyIn
      name: kubectl-resource-usage
    commit_author:
      name: r1ckyIn
      email: rickyqin919@gmail.com
    homepage: https://github.com/r1ckyIn/kubectl-resource-usage
    short_description: Display Pod CPU/Memory usage percentage
    description: |
      A kubectl plugin that displays Pod-level CPU/Memory resource usage
      percentages. Unlike `kubectl top pods` which only shows raw values,
      this plugin calculates usage percentages relative to requests and limits,
      helping SREs quickly identify resource issues.

      Features:
      - Calculate CPU/Memory Request% and Limit%
      - Filter by namespace (-n) or label selector (-l)
      - Sort by CPU or Memory usage rate (--sort)
      - Multiple output formats: table, json, yaml, wide
      - Filter by usage threshold (--above, --below)
      - Find pods without limits configured (--no-limits)
    skip_upload: true
